### ISSUE TITLE
Complete the Back-End

### ISSUE THREAD

**Issue by adimacci95** [christinenia/Project-1#4]
1. Add Webscrapper (e.g., API, AJAX)
2. Retrieve and apply the API from Dwell/New York Times
    * If there is time, create subscribe buttons for each resource or establish links to the articles revolving around the client
3. Establish Firebase for contact info/CRM
4. Plug in the DOM

**Comment by aaquino909** [comment]
article for adding Rss feed in javascript
https://www.raymondcamden.com/2015/12/08/parsing-rss-feeds-in-javascript-options

**Comment by aaquino909** [comment]
https://console.firebase.google.com/project/ucla-extension-test-1/overview?pli=1

6 articles pulling from JSON of Rss feed from dwell 
give access from edeers firebase

psuedocode for live articles
1.
